pipeline {
  agent any
  stages {
    stage("Install") {
      steps {
        dir('app') {
          bat 'npm ci'
        }
      }
    }
    stage("Lint & Test") {
      parallel {
        stage("Lint") {
          steps {
            dir('app') {
              bat 'npm run lint'
            }
          }
        }
        stage("Test") {
          steps {
            dir('app') {
              bat 'npm test'
            }
          }
        }
      }
    }
  }
}