pipeline {
  agent any
  stages {
    stage("Install") {
      steps {
        dir('app') {
          bat 'npm ci'
        }
      }
    }
    stage("Lint") {
      steps {
        dir('app') {
          bat 'npm run lint'
        }
      }
    }
    stage("Test") {
      steps {
        dir('app') {
          bat 'npm test'
        }
      }
    }
  }
}