pipeline {
  agent any
  stages {
    stage("Install") {
      steps {
        bat 'npm ci'
      }
    }
    stage("Lint") {
      steps {
        bat 'npm run lint'
      }
    }
    stage("Test") {
      steps {
        bat 'npm test'
      }
    }
  }
}